### ISSUE TITLE
Direct Message Text getting cut off with Screen Readers (Specifically NVDA)

### ISSUE THREAD

**Issue by masonasons** [opentween/OpenTween#37]
Make it possible to display the text of a dm in a message box with a hotkey or menu item. If a dm is too long, it is cut off by screen readers such as NVDA and the only way to read it as of now is by copying the dm (Control+C) into notepad and reading it that way.

**Comment by masonasons** [comment]
The maximum amount of characters shown on a long dm before being cut off is 259 characters.

**Comment by upsilon** [comment]
You can read a DM that is longer than 259 characters by Ctrl+C and NVDA+C instead of using notepad.

Since NVDA always allocates 260 bytes of buffer, the text of the ListView beyond 259 characters (+ null character) will not be acquired.

https://github.com/nvaccess/nvda/blob/release-2017.1/source/NVDAObjects/IAccessible/sysListView32.py#L73:
```python
CBEMAXSTRLEN=260
```
